import { Track } from "@/types";

export const tracks: Track[] = [
  {
    id: "head-voor",
    title: "Head Voor",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/Head-Voor.mp3",
  },
  {
    id: "hanu",
    title: "Hanu",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/Hanu.mp3",
  },
  {
    id: "moshkel",
    title: "Moshkel",
    titleFa: "مشکل",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/Moshkel.mp3",
  },
  {
    id: "pelak-taviz",
    title: "Pelak Taviz",
    titleFa: "پلاک تعویض",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/Pelak-Taviz.mp3",
  },
  {
    id: "sabz",
    title: "Sabz",
    titleFa: "سبز",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/Sabz.mp3",
  },
  {
    id: "goosh-bedeh",
    title: "Goosh Bedeh",
    titleFa: "گوش بده",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/Goosh-Bedeh.mp3",
  },
  {
    id: "rady",
    title: "Rady",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
     downloadUrl: "/music/Rady.mp3",
  },
  {
    id: "rok",
    title: "Rok",
    featuring: ["Metti"],
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/Rok.mp3",
  },
  {
    id: "come-back",
    title: "Come Back",
    featuring: ["Metti"],
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/Come-Back.mp3",
  },
  {
    id: "nemidoonam",
    title: "Nemidoonam",
    titleFa: "نمیدونم",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/Nemidoonam.mp3",
  },
  {
    id: "benal",
    title: "Benal",
    genre: "Azerbaijani Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/benal.mp3",
  },
  {
    id: "bahsi-ni",
    title: "Bahsi Ni",
    genre: "Azerbaijani Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/Bahsi-Ni.mp3",
  },
  {
    id: "jangi",
    title: "Jangi",
    titleFa: "جنگی",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/Jangi.mp3",
  },
  {
    id: "rassam",
    title: "Rassam",
    titleFa: "رسام",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/Rassam.mp3",
  },
  {
    id: "mashghi",
    title: "Mashghi",
    titleFa: "مشغی",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/Mashghi.mp3",
  },
  {
    id: "lash-gusht",
    title: "Lash Gusht",
    titleFa: "لاش گشت",
    featuring: ["Wonder"],
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/Lash-Gusht.mp3",
  },
  {
    id: "otagh",
    title: "Otagh",
    titleFa: "اتاق",
    genre: "Persian Rap / Azerbaijani Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/Otagh.mp3",
  },
  {
    id: "kalameh",
    title: "Kalameh",
    titleFa: "کلمه",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/Kalameh.mp3",
  },
];

export const socialLinks = [
  {
    platform: "SoundCloud",
    url: "https://soundcloud.com/ali-alipoor-141068609",
    handle: "RALIPNIC",
  },
  {
    platform: "Telegram",
    url: "https://t.me/ralipnicofficial",
    handle: "@ralipnicofficial",
  },
  {
    platform: "Instagram",
    url: "https://instagram.com/ralipnic",
    handle: "@ralipnic",
  },
];
