import { Track } from "@/types";

export const tracks: Track[] = [
  {
    id: "head-voor",
    title: "Head Voor",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/head voor.mp3",
  },
  {
    id: "hanu",
    title: "Hanu",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/hanu.mp3",
  },
  {
    id: "moshkel",
    title: "Moshkel",
    titleFa: "مشکل",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/moshkel.mp3",
  },
  {
    id: "pelak-taviz",
    title: "Pelak Taviz",
    titleFa: "پلاک تعویض",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/pelak taviz.mp3",
  },
  {
    id: "sabz",
    title: "Sabz",
    titleFa: "سبز",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/sabz.mp3",
  },
  {
    id: "goosh-bedeh",
    title: "Goosh Bedeh",
    titleFa: "گوش بده",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/goosh bedeh.mp3",
  },
  {
    id: "rady",
    title: "Rady",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
     downloadUrl: "/music/rady.mp3",
  },
  {
    id: "rok",
    title: "Rok",
    featuring: ["Metti"],
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/rok.mp3",
  },
  {
    id: "come-back",
    title: "Come Back",
    featuring: ["Metti"],
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/come back.mp3",
  },
  {
    id: "nemidoonam",
    title: "Nemidoonam",
    titleFa: "نمیدونم",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/nemidoonam.mp3",
  },
  {
    id: "benal",
    title: "Benal",
    genre: "Azerbaijani Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/benal.mp3",
  },
  {
    id: "bahsi-ni",
    title: "Bahsi Ni",
    genre: "Azerbaijani Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/bahsi ni.mp3",
  },
  {
    id: "jangi",
    title: "Jangi",
    titleFa: "جنگی",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/jangi.mp3",
  },
  {
    id: "rassam",
    title: "Rassam",
    titleFa: "رسام",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/rassam.mp3",
  },
  {
    id: "mashghi",
    title: "Mashghi",
    titleFa: "مشغی",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/mashghi.mp3",
  },
  {
    id: "lash-gusht",
    title: "Lash Gusht",
    titleFa: "لاش گشت",
    featuring: ["Wonder"],
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/lash gusht.mp3",
  },
  {
    id: "otagh",
    title: "Otagh",
    titleFa: "اتاق",
    genre: "Persian Rap / Azerbaijani Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/otagh.mp3",
  },
  {
    id: "kalameh",
    title: "Kalameh",
    titleFa: "کلمه",
    genre: "Persian Rap",
    soundcloudUrl: "https://soundcloud.com/ali-alipoor-141068609",
    downloadUrl: "/music/kalameh.mp3",
  },
];

export const socialLinks = [
  {
    platform: "SoundCloud",
    url: "https://soundcloud.com/ali-alipoor-141068609",
    handle: "RALIPNIC",
  },
  {
    platform: "Telegram",
    url: "https://t.me/ralipnicofficial",
    handle: "@ralipnicofficial",
  },
  {
    platform: "Instagram",
    url: "https://instagram.com/ralipnic",
    handle: "@ralipnic",
  },
];
